[package]
name = "rs-for-reals2ipc"
version = "0.1.0"
edition = "2024"

description = "Converts the FoR encoded reals to an arrow ipc array."
license = "Apache-2.0"
repository = "https://github.com/takanoriyanagitani/rs-for-reals2ipc"
homepage = "https://github.com/takanoriyanagitani/rs-for-reals2ipc"
documentation = "https://docs.rs/rs-for-reals2ipc/latest"
keywords = ["arrow", "ipc", "float", "FoR", "convert"]

exclude = [
]

[profile.release-wasi]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 1

[[bin]]
name = "for-reals2ipc"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"

[dependencies.arrow-array]
version = "60.0"
default-features = false
features = [
]

[dependencies.arrow-schema]
version = "60.0"
default-features = false
features = [
]

[dependencies.arrow-ipc]
version = "60.0"
default-features = false
features = [
]

[features]
ipc-zstd = [
  "arrow-ipc/zstd",
]
